/**
 * Description:
 * Draw fractal pattern
 * Zoom In - left click
 * Zoom out - right click
 * 
 * Developed by : Donghyeok Seo
 * Date : 2020. 03. 05
 */
package pkgtrianglebuildfractal;

import java.awt.Dimension;
import javax.swing.SwingUtilities;

public class TriangleBuildFractal extends javax.swing.JFrame {

    /**
     * Creates new form Day07TriangleBuildFractal
     */
    public TriangleBuildFractal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        triangleFractalCanvas1 = new pkgtrianglebuildfractal.TriangleFractalCanvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout triangleFractalCanvas1Layout = new javax.swing.GroupLayout(triangleFractalCanvas1);
        triangleFractalCanvas1.setLayout(triangleFractalCanvas1Layout);
        triangleFractalCanvas1Layout.setHorizontalGroup(
            triangleFractalCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        triangleFractalCanvas1Layout.setVerticalGroup(
            triangleFractalCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(triangleFractalCanvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(triangleFractalCanvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int power = 0;
    private double scale = 1.5;
    int startPointX = 0;
    int startPointY = 0;
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        int width = triangleFractalCanvas1.getWidth();
        int height = triangleFractalCanvas1.getHeight();
        int mouseX = evt.getX() - 7;// substitude window border
        int mouseY = evt.getY() - 31;// substitude window top bar

        int trueX = startPointX + mouseX;
        int trueY = startPointY + mouseY;

        if(SwingUtilities.isLeftMouseButton(evt)){
            System.out.println("Zoom In");

            triangleFractalCanvas1.setSize(new Dimension((int)(width * scale),(int)(height * scale)));
            
            trueX *= scale;
            trueY *= scale;

            startPointX = trueX - mouseX;
            startPointY = trueY - mouseY;
            
            triangleFractalCanvas1.setLocation(
                    (-1)*startPointX,(-1)*startPointY
            );
        } else if( SwingUtilities.isRightMouseButton(evt)){
            if( width <= this.getWidth() || height <= this.getHeight()){ return; }
            System.out.println("Zoom out");

            triangleFractalCanvas1.setSize(new Dimension((int)(width / scale),(int)(height / scale)));
            
            trueX /= scale;
            trueY /= scale;

            startPointX = trueX - mouseX;
            startPointY = trueY - mouseY;
         
            triangleFractalCanvas1.setLocation(
                    (-1)*startPointX,(-1)*startPointY
            );
        }
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriangleBuildFractal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriangleBuildFractal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriangleBuildFractal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriangleBuildFractal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriangleBuildFractal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkgtrianglebuildfractal.TriangleFractalCanvas triangleFractalCanvas1;
    // End of variables declaration//GEN-END:variables
}
