/**
 * Description:
 * Draw fractal pattern
 * Zoom In - left click
 * Zoom out - right click
 * 
 * Developed by : Donghyeok Seo
 * Date : 2020. 03. 05
 */
package pkgtrianglebuildfractal;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.geom.AffineTransform;

public class TriangleFractalCanvas extends javax.swing.JPanel {

    public TriangleFractalCanvas() {
        //initComponents();
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(600, 600);
    }
    
    public void doubleCanvas(){
        AffineTransform scaleDouble = new AffineTransform();
        scaleDouble.scale(2, 2);
        g2d.transform(scaleDouble);
    }
    
    Graphics2D g2d;
    
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        int width = getWidth();
        int height = getHeight();
        
        g2d = (Graphics2D) g.create();
        
        g2d.translate(0, height/2);
        g2d.drawLine(0,0, width, 0);
        drawTriangleFractal(g2d,1,width/3);
        
        g2d.dispose();
    }
    
    private final int WINDOW_WIDTH = 600;
    private final int WINDOW_HEIGHT = 600;
    
    private void drawTriangleFractal(Graphics2D g2d, int reverse, double length){
        if(length < 2){ return; }
        
        this.getMousePosition();
        
        Point mousePoint = this.getMousePosition();
        AffineTransform afTransForm = g2d.getTransform();
        
        // TODO: Don't draw anything outside of window(WIP)
//        if( mousePoint != null ){
//            System.out.printf(
//                    "mouseX: %f, mouseY: %f\n"
//                    + "transX: %f,transY: %f",
//                    mousePoint.getX(),mousePoint.getY(),
//                    afTransForm.getTranslateX(), afTransForm.getTranslateY()
//            );
//            if(Math.abs(afTransForm.getTranslateX()) > mousePoint.getX() + WINDOW_WIDTH
//                || Math.abs(afTransForm.getTranslateX()) < mousePoint.getX() - WINDOW_WIDTH
//                || Math.abs(afTransForm.getTranslateY()) > mousePoint.getY() + WINDOW_HEIGHT
//                || Math.abs(afTransForm.getTranslateY()) < mousePoint.getY() - WINDOW_HEIGHT)
//            { return; }
//            
//        }
        
        // Draw left side line
        drawTriangleFractal(g2d, reverse, length/3);
        g2d.setTransform(afTransForm); // go back to the position

        // Draw triangle
        //1. Move to next point
        g2d.translate(length,0);
        afTransForm = g2d.getTransform();// Save position
        
        //2-1. Draw left side of triangle
        g2d.rotate(-Math.PI*1/3 * reverse);
        g2d.drawLine(0,0, (int)length, 0);
        
        //2-2. Draw triangle on the left side of triangle
        drawTriangleFractal(g2d, reverse, length/3);
        
        //3. Move to next point
        g2d.setTransform(afTransForm);// to back to the position after rotate
        g2d.translate(length,0);
        afTransForm = g2d.getTransform();// Save position
        
        //4-1. Draw right side of triangle
        g2d.rotate(-Math.PI*2/3 * reverse);
        g2d.drawLine(0,0, (int)length, 0);
        
        //4-2. Draw triangle on the right side of triangle
        drawTriangleFractal(g2d, reverse* (-1), length/3);

        //5. Draw left side of triangle
        g2d.setTransform(afTransForm);
        drawTriangleFractal(g2d, reverse, length/3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1000, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
