/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgLibrary;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author heokc
 */
enum Button { Checkout,Return}
public class PenalDlgCheckout extends javax.swing.JPanel {
    DefaultListModel<Member> modelMemberList = new DefaultListModel<>();
    DefaultListModel<Book> modelBookList = new DefaultListModel<>();
    
    Member crtMember;
    Book crtBook;
    
    public Button dlgFor;
    
    Database db;
    /**
     * Creates new form PenalDlgCheckout
     */
    public PenalDlgCheckout() {
        initComponents();
        
        try{
            db = DatabaseManager.getDatabaseInstance();
            
        }catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Cannot connect Dababase(CheckOut). Program exit",
                    "DABABASE ERROR",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
    }
    void initDlgCheckoutTaps(){
        tabbedPanel.setSelectedIndex(0);
        tabbedPanel.setEnabledAt(0,true);
        tabbedPanel.setEnabledAt(1,false);
        tabbedPanel.setEnabledAt(2,false);
        
        pnMember_lstMember.setSelectedValue(null,false);
        pnBook_lstBook.setSelectedValue(null,false);
    }
    void reloadMemberList(){
        try{
            modelMemberList.clear();
            switch(dlgFor){
                case Checkout:
                    modelMemberList.addAll(db.getMemberList());
                    break;
                case Return:
                    modelMemberList.addAll(db.getLoaningMemberList());
                    break;
                default:
                    JOptionPane.showMessageDialog(this,
                        "Should not happen",
                        "INTERNAL ERROR",
                        JOptionPane.ERROR_MESSAGE
                    );
            }
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Cannot read data",
                    "ERROR Data load",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    void reloadBookList(){
        try{
            modelBookList.clear();
            modelBookList.addAll(db.getBookList());
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Cannot read data",
                    "ERROR Data load(Checkout)",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    void reloadBookListOfMember(int memberId){
        try{
            modelBookList.clear();
            modelBookList.addAll(db.getLoaningBookList(memberId));
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Cannot read data",
                    "ERROR Data load(Checkout)",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpDueDay = new javax.swing.ButtonGroup();
        tabbedPanel = new javax.swing.JTabbedPane();
        pnMember = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnMember_lstMember = new javax.swing.JList<>();
        pnMember_btBack = new javax.swing.JButton();
        pnMember_btNext = new javax.swing.JButton();
        pnBook = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnBook_lstBook = new javax.swing.JList<>();
        pnBook_btBack = new javax.swing.JButton();
        pnBook_btNext = new javax.swing.JButton();
        pnConfirm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnConfirm_lblChosenMember = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnConfirm_lblChosenBook = new javax.swing.JLabel();
        pnConfirm_lblFinishMsg = new javax.swing.JLabel();
        pnConfirm_btBack = new javax.swing.JButton();
        pnConfirm_btFinish = new javax.swing.JButton();
        pnConfirm_pnDueDate = new javax.swing.JPanel();
        pnConfirm_rb60 = new javax.swing.JRadioButton();
        pnConfirm_rb30 = new javax.swing.JRadioButton();
        pnConfirm_rb10 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        pnConfirm_rb90 = new javax.swing.JRadioButton();
        pnConfirm_rb20 = new javax.swing.JRadioButton();

        setLayout(new java.awt.CardLayout());

        pnMember.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnMemberComponentShown(evt);
            }
        });

        pnMember_lstMember.setModel(modelMemberList);
        pnMember_lstMember.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pnMember_lstMember.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                pnMember_lstMemberValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(pnMember_lstMember);

        pnMember_btBack.setText("Back");
        pnMember_btBack.setEnabled(false);
        pnMember_btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnMember_btBackActionPerformed(evt);
            }
        });

        pnMember_btNext.setText("Next");
        pnMember_btNext.setEnabled(false);
        pnMember_btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnMember_btNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMemberLayout = new javax.swing.GroupLayout(pnMember);
        pnMember.setLayout(pnMemberLayout);
        pnMemberLayout.setHorizontalGroup(
            pnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMemberLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnMember_btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnMember_btNext)))
                .addContainerGap())
        );

        pnMemberLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnMember_btBack, pnMember_btNext});

        pnMemberLayout.setVerticalGroup(
            pnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnMember_btBack)
                    .addComponent(pnMember_btNext))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Choose member", pnMember);

        pnBook.setEnabled(false);
        pnBook.setFocusable(false);
        pnBook.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnBookComponentShown(evt);
            }
        });

        pnBook_lstBook.setModel(modelBookList);
        pnBook_lstBook.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pnBook_lstBook.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                pnBook_lstBookValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(pnBook_lstBook);

        pnBook_btBack.setText("Back");
        pnBook_btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnBook_btBackActionPerformed(evt);
            }
        });

        pnBook_btNext.setText("Next");
        pnBook_btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnBook_btNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBookLayout = new javax.swing.GroupLayout(pnBook);
        pnBook.setLayout(pnBookLayout);
        pnBookLayout.setHorizontalGroup(
            pnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBookLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnBook_btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnBook_btNext)))
                .addContainerGap())
        );

        pnBookLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnBook_btBack, pnBook_btNext});

        pnBookLayout.setVerticalGroup(
            pnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnBook_btBack)
                    .addComponent(pnBook_btNext))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Choose book", pnBook);

        pnConfirm.setEnabled(false);

        jLabel1.setText("Member chosen: ");

        jLabel3.setText("Book chosen: ");

        pnConfirm_lblFinishMsg.setText("Pressing finish will loan the book.");

        pnConfirm_btBack.setText("Back");
        pnConfirm_btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnConfirm_btBackActionPerformed(evt);
            }
        });

        pnConfirm_btFinish.setText("Finish");
        pnConfirm_btFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnConfirm_btFinishActionPerformed(evt);
            }
        });

        btnGrpDueDay.add(pnConfirm_rb60);
        pnConfirm_rb60.setText("60");

        btnGrpDueDay.add(pnConfirm_rb30);
        pnConfirm_rb30.setText("30");

        btnGrpDueDay.add(pnConfirm_rb10);
        pnConfirm_rb10.setSelected(true);
        pnConfirm_rb10.setText("10");

        jLabel5.setText("To be returned in this many days: ");

        btnGrpDueDay.add(pnConfirm_rb90);
        pnConfirm_rb90.setText("90");

        btnGrpDueDay.add(pnConfirm_rb20);
        pnConfirm_rb20.setText("20");

        javax.swing.GroupLayout pnConfirm_pnDueDateLayout = new javax.swing.GroupLayout(pnConfirm_pnDueDate);
        pnConfirm_pnDueDate.setLayout(pnConfirm_pnDueDateLayout);
        pnConfirm_pnDueDateLayout.setHorizontalGroup(
            pnConfirm_pnDueDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConfirm_pnDueDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnConfirm_pnDueDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnConfirm_pnDueDateLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnConfirm_rb10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnConfirm_rb20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnConfirm_rb30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnConfirm_rb60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnConfirm_rb90))
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        pnConfirm_pnDueDateLayout.setVerticalGroup(
            pnConfirm_pnDueDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConfirm_pnDueDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnConfirm_pnDueDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnConfirm_rb20)
                    .addComponent(pnConfirm_rb30)
                    .addComponent(pnConfirm_rb60)
                    .addComponent(pnConfirm_rb10)
                    .addComponent(pnConfirm_rb90))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnConfirmLayout = new javax.swing.GroupLayout(pnConfirm);
        pnConfirm.setLayout(pnConfirmLayout);
        pnConfirmLayout.setHorizontalGroup(
            pnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnConfirmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnConfirm_lblFinishMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnConfirmLayout.createSequentialGroup()
                        .addComponent(pnConfirm_btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnConfirm_btFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGap(21, 21, 21))
            .addGroup(pnConfirmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnConfirm_lblChosenMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnConfirm_lblChosenBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnConfirmLayout.createSequentialGroup()
                        .addGroup(pnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(pnConfirm_pnDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnConfirmLayout.setVerticalGroup(
            pnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConfirmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnConfirm_lblChosenMember, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnConfirm_lblChosenBook, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnConfirm_pnDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnConfirm_lblFinishMsg)
                .addGap(18, 18, 18)
                .addGroup(pnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnConfirm_btFinish)
                    .addComponent(pnConfirm_btBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Confirm", pnConfirm);

        add(tabbedPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void pnMemberComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnMemberComponentShown
       
    }//GEN-LAST:event_pnMemberComponentShown

    private void pnBookComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnBookComponentShown
        
    }//GEN-LAST:event_pnBookComponentShown

    private void pnMember_btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnMember_btBackActionPerformed
        
    }//GEN-LAST:event_pnMember_btBackActionPerformed

    private void pnMember_lstMemberValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_pnMember_lstMemberValueChanged
        Member selMember = pnMember_lstMember.getSelectedValue();
        if(selMember == null){
            pnMember_btNext.setEnabled(false);
            return;
        }
        
        crtMember = selMember;
        pnConfirm_lblChosenMember.setText(selMember.toString());
        pnMember_btNext.setEnabled(true);
    }//GEN-LAST:event_pnMember_lstMemberValueChanged

    private void pnMember_btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnMember_btNextActionPerformed
        Member member = pnMember_lstMember.getSelectedValue();
        if(member == null){
            JOptionPane.showMessageDialog(this,
                    "Select one member",
                    "Error Member",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if(!member.isAbleToLoan() && dlgFor == Button.Checkout){
            JOptionPane.showMessageDialog(this,
                    "This member loans Max amount of books",
                    "Loan is not avaliable",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if(dlgFor == Button.Checkout){
            reloadBookList();
        } else {
            reloadBookListOfMember(member.getId());
        }
        goNextTabbedPanel();
    }//GEN-LAST:event_pnMember_btNextActionPerformed

    private void pnBook_btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnBook_btNextActionPerformed
        goNextTabbedPanel();
    }//GEN-LAST:event_pnBook_btNextActionPerformed

    private void pnBook_btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnBook_btBackActionPerformed
        goPreviousTabbedPanel();
    }//GEN-LAST:event_pnBook_btBackActionPerformed

    private void pnConfirm_btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnConfirm_btBackActionPerformed
        goPreviousTabbedPanel();
    }//GEN-LAST:event_pnConfirm_btBackActionPerformed

    private void pnBook_lstBookValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_pnBook_lstBookValueChanged
        Book selBook = pnBook_lstBook.getSelectedValue();
        if(selBook == null){ 
            pnBook_btNext.setEnabled(false);
            return; 
        }
        
        if(!selBook.isAbleToBorrow() && dlgFor == Button.Checkout){
            JOptionPane.showMessageDialog(this,
                    "This book is not avaliable",
                    "Loan is not avaliable",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        crtBook = selBook;
        pnConfirm_lblChosenBook.setText(selBook.toString());
        pnBook_btNext.setEnabled(true);
        
        // Change Confirmation tab Message
        switch(dlgFor){
            case Checkout:
                pnConfirm_lblFinishMsg.setText("Pressing finish will loan the book.");
                pnConfirm_pnDueDate.setVisible(true);
                break;
            case Return:
                pnConfirm_lblFinishMsg.setText("Pressing finish will return the book.");
                pnConfirm_pnDueDate.setVisible(false);
                break;
            default:
        }
    }//GEN-LAST:event_pnBook_lstBookValueChanged

    private void pnConfirm_btFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnConfirm_btFinishActionPerformed
        try {
            switch(dlgFor){
                case Checkout:
                    String dueDayStr;
                    if(pnConfirm_rb10.isSelected()){
                        dueDayStr = "10";
                    } else if(pnConfirm_rb20.isSelected()){
                        dueDayStr = "20";
                    } else if(pnConfirm_rb30.isSelected()){
                        dueDayStr = "30";
                    } else if(pnConfirm_rb60.isSelected()){
                        dueDayStr = "60";
                    } else if(pnConfirm_rb90.isSelected()){
                        dueDayStr = "90";
                    } else{
                        JOptionPane.showMessageDialog(this,
                                "Shouldn't happen",
                                "INTERNAL ERROR",
                                JOptionPane.ERROR_MESSAGE
                        );
                        return;
                    }

                    db.checkoutBook(crtMember,crtBook,Integer.parseInt(dueDayStr));
                    break;
                case Return:
                    db.returnBook(crtMember,crtBook);
                    break;
                default:
                    System.out.println("INTERNAL ERROR: Should not happen!");
                    
            }
           
            
        } catch (SQLException|CheckoutBookException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                        "Cannot Checkout. " + ex.getMessage(),
                        "Checkout ERROR",
                        JOptionPane.ERROR_MESSAGE
                );
        } finally {
            JDialog window = (JDialog)SwingUtilities.getAncestorOfClass(JDialog.class, this);
            window.dispose();
        }
    }//GEN-LAST:event_pnConfirm_btFinishActionPerformed
    
    void goNextTabbedPanel(){
        int index = tabbedPanel.getSelectedIndex();
        if(tabbedPanel.getComponentAt(index+1) == null){return; }
        
        tabbedPanel.setSelectedIndex(index + 1);
        tabbedPanel.setEnabledAt(index, false);
        tabbedPanel.setEnabledAt(index+1, true);
    }
    
    void goPreviousTabbedPanel(){
        int index = tabbedPanel.getSelectedIndex();
        if(tabbedPanel.getComponentAt(index-1) == null){return; }
        
        tabbedPanel.setSelectedIndex(index - 1);
        tabbedPanel.setEnabledAt(index, false);
        tabbedPanel.setEnabledAt(index-1, true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpDueDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnBook;
    private javax.swing.JButton pnBook_btBack;
    private javax.swing.JButton pnBook_btNext;
    private javax.swing.JList<Book> pnBook_lstBook;
    private javax.swing.JPanel pnConfirm;
    private javax.swing.JButton pnConfirm_btBack;
    private javax.swing.JButton pnConfirm_btFinish;
    private javax.swing.JLabel pnConfirm_lblChosenBook;
    private javax.swing.JLabel pnConfirm_lblChosenMember;
    private javax.swing.JLabel pnConfirm_lblFinishMsg;
    private javax.swing.JPanel pnConfirm_pnDueDate;
    private javax.swing.JRadioButton pnConfirm_rb10;
    private javax.swing.JRadioButton pnConfirm_rb20;
    private javax.swing.JRadioButton pnConfirm_rb30;
    private javax.swing.JRadioButton pnConfirm_rb60;
    private javax.swing.JRadioButton pnConfirm_rb90;
    private javax.swing.JPanel pnMember;
    private javax.swing.JButton pnMember_btBack;
    private javax.swing.JButton pnMember_btNext;
    private javax.swing.JList<Member> pnMember_lstMember;
    private javax.swing.JTabbedPane tabbedPanel;
    // End of variables declaration//GEN-END:variables
}
