
package pkgLibrary;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class PenalDlgRentedBook extends javax.swing.JPanel {

    DefaultComboBoxModel<Show> modelShowComboList = new DefaultComboBoxModel<>(Show.values());
    DefaultComboBoxModel<SortBy> modelSortByComboList = new DefaultComboBoxModel<>(SortBy.values());
    DefaultListModel<Loan> modelLoanList = new DefaultListModel<>();
    
    Database db;
    /**
     * Implements methods
     * 
     * Method 1. 
     * - Get all loans and related members and books => Array 
     * - check database changes (database trigger(or insert data from Java) and extra table)
     * - reload only modified data
     * 
     * Method 2.
     * - Reload Data all the time combo box value changes
     */
    
    public PenalDlgRentedBook() {
        initComponents();
        
        try{
            db = DatabaseManager.getDatabaseInstance();

        } catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Cannot connect Dababase(ManageMember). Program exit",
                    "DABABASE ERROR",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    void reloadLoanList(){
        try{
            if((SortBy)comboSortBy.getSelectedItem() == SortBy.Popularity){
                JOptionPane.showMessageDialog(this,
                        "This feature is coming Soon",
                        "Comming Soon Feature",
                        JOptionPane.PLAIN_MESSAGE
                );
                return;
            }
            ArrayList<Loan> loanList 
                    = db.showBooksRented(
                            (Show)comboShow.getSelectedItem(), 
                            (SortBy)comboSortBy.getSelectedItem()
                    );
            modelLoanList.clear();
            modelLoanList.addAll(loanList);
        } catch ( SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Cannot connect Dababase(ManageMember).",
                    "DABABASE ERROR",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboShow = new javax.swing.JComboBox<>();
        comboSortBy = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMemberLoan = new javax.swing.JList<>();
        btDismiss = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        comboShow.setModel(modelShowComboList);
        comboShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboShowActionPerformed(evt);
            }
        });

        comboSortBy.setModel(modelSortByComboList);
        comboSortBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSortByActionPerformed(evt);
            }
        });

        lstMemberLoan.setModel(modelLoanList);
        lstMemberLoan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstMemberLoan);

        btDismiss.setText("Dismiss");
        btDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDismissActionPerformed(evt);
            }
        });

        jLabel1.setText("Show:");

        jLabel2.setText("Sort by:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboShow, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(btDismiss)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDismiss)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDismissActionPerformed
        JDialog window = (JDialog) SwingUtilities.getAncestorOfClass(JDialog.class, this);
        window.dispose();
    }//GEN-LAST:event_btDismissActionPerformed

    private void comboSortByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSortByActionPerformed
        reloadLoanList();
    }//GEN-LAST:event_comboSortByActionPerformed

    private void comboShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboShowActionPerformed
        reloadLoanList();
    }//GEN-LAST:event_comboShowActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDismiss;
    private javax.swing.JComboBox<Show> comboShow;
    private javax.swing.JComboBox<SortBy> comboSortBy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Loan> lstMemberLoan;
    // End of variables declaration//GEN-END:variables
}
