/**
 * Program : Student Manager program.
 * Purpose : Add, Edit student's information(Regular : name, grades, card : permanent code, photo) 
 * Restriction : valid grade(white space, "," delimiter)
 *               Each student has only one card
 * 
 * Script by : Donghyeok Seo
 * Date : 2020.02.25
 */

package pkgStudentInfoManager;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;

import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class StudentInfoManager extends javax.swing.JFrame {

    private final Pattern imgExtPtn = Pattern.compile("\\.(jpg|jpeg|png|gif)$");
    // set file filter for *.jpg, *.jpeg, *.gif, *.png extentions 
    private final FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Image file(*.jpg, *.jpeg, *.gif, *.png)",
             "jpg", "jpeg", "gif", "png"
    );

    private final String DEFAULT_PHOTO_MESSAGE = "150x150 pixels, clickable";

    DefaultListModel<Student> modelStudentList = new DefaultListModel<>();
    Database db;
    BufferedImage bufImg;
    
    public StudentInfoManager() {
        initComponents();

        try {
            db = new Database();

            modelStudentList.addAll(db.getAllStudentList());
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to Database.\n Program exit.",
                    "DATABASE CONNECTION ERROR",
                    JOptionPane.ERROR_MESSAGE
            );
            System.exit(1);
        }
        fileChooser.setFileFilter(filter);
    }
// convert image size to 150x150, return converted Image

    public static BufferedImage convertImgSize(BufferedImage originalImg) {
        BufferedImage newImg = new BufferedImage(100, 100, originalImg.getType());
        Graphics2D g = newImg.createGraphics();
        g.drawImage(originalImg.getScaledInstance(100, 100, Image.SCALE_SMOOTH), null, null);
        g.dispose();

        return newImg;
    }

    // Choose Image with file chooser(filter :*.jpg, *.jpeg, *.gif, *.png)
    private File chooseImageFile() {
        if (fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return null;
        }

        File chosenImgFile = fileChooser.getSelectedFile();
        if (chosenImgFile == null) {
            JOptionPane.showMessageDialog(this,
                    "Please choose image that you want to add",
                    "No Image is chosen",
                    JOptionPane.ERROR_MESSAGE
            );
            return null;
        }
        return chosenImgFile;

    }

    // Check if file extention is in *.jpg, *.jpeg, *.gif, *.png
    private boolean isValidImgFile(File file) {
        Matcher m = imgExtPtn.matcher(file.getName());
        if (!m.find()) {
            JOptionPane.showMessageDialog(this,
                    "Not supported Image file chosen:" + file.getName(),
                    "No Image chosen",
                    JOptionPane.ERROR_MESSAGE
            );
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCard = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dlgCard_lblIdVal = new javax.swing.JLabel();
        dlgCard_tfPermCode = new javax.swing.JTextField();
        dlgCard_lblPhotoVal = new javax.swing.JLabel();
        dlgCard_btAddCard = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStudents = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIdVal = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taGrades = new javax.swing.JTextArea();
        lblPhotoVal = new javax.swing.JLabel();
        btAddCard = new javax.swing.JButton();
        btAddStudent = new javax.swing.JButton();
        btUpdateStudent = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblGpa = new javax.swing.JLabel();

        dlgCard.setResizable(false);
        dlgCard.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dlgCardWindowClosing(evt);
            }
        });

        jLabel5.setText("ID:");

        jLabel6.setText("Perm Code:");

        jLabel7.setText("Photo:");

        dlgCard_lblIdVal.setText("-");

        dlgCard_lblPhotoVal.setText("100x100");
        dlgCard_lblPhotoVal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dlgCard_lblPhotoVal.setPreferredSize(new java.awt.Dimension(100, 100));
        dlgCard_lblPhotoVal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dlgCard_lblPhotoValMouseClicked(evt);
            }
        });

        dlgCard_btAddCard.setText("Add Card");
        dlgCard_btAddCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgCard_btAddCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCardLayout = new javax.swing.GroupLayout(dlgCard.getContentPane());
        dlgCard.getContentPane().setLayout(dlgCardLayout);
        dlgCardLayout.setHorizontalGroup(
            dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dlgCard_btAddCard)
                    .addGroup(dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(dlgCardLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dlgCard_lblIdVal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dlgCardLayout.createSequentialGroup()
                            .addGroup(dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dlgCard_lblPhotoVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dlgCard_tfPermCode)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        dlgCardLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7});

        dlgCardLayout.setVerticalGroup(
            dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dlgCard_lblIdVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dlgCard_tfPermCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dlgCard_lblPhotoVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dlgCard_btAddCard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lstStudents.setModel(modelStudentList);
        lstStudents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstStudents.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstStudentsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstStudents);

        jLabel1.setText("ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Grades:");

        jLabel4.setText("Photo:");

        lblIdVal.setText("-");

        taGrades.setColumns(10);
        taGrades.setRows(4);
        taGrades.setPreferredSize(new java.awt.Dimension(5, 22));
        jScrollPane2.setViewportView(taGrades);

        lblPhotoVal.setText("100x100");
        lblPhotoVal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPhotoVal.setPreferredSize(new java.awt.Dimension(100, 100));

        btAddCard.setText("Add Id Card");
        btAddCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCardActionPerformed(evt);
            }
        });

        btAddStudent.setText("Add Student");
        btAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddStudentActionPerformed(evt);
            }
        });

        btUpdateStudent.setText("Update Student");
        btUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateStudentActionPerformed(evt);
            }
        });

        jLabel8.setText("GPA:");

        lblGpa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGpa.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblIdVal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAddCard, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhotoVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblIdVal))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblGpa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblPhotoVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(btAddCard)
                        .addGap(7, 7, 7)
                        .addComponent(btAddStudent)
                        .addGap(6, 6, 6)
                        .addComponent(btUpdateStudent)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCardActionPerformed
        dlgCard.setLocation(this.getLocation());
        this.setEnabled(false);
        dlgCard.pack();
        dlgCard.setVisible(true);
    }//GEN-LAST:event_btAddCardActionPerformed

    private void dlgCardWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgCardWindowClosing
        this.setEnabled(true);
    }//GEN-LAST:event_dlgCardWindowClosing

    private void lstStudentsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstStudentsValueChanged

        final String defaultMsgPhoto = "100x100";

        Student selStd = lstStudents.getSelectedValue();
        if (selStd == null) {
            lblPhotoVal.setIcon(null);
            lblPhotoVal.setText(defaultMsgPhoto);
            lblIdVal.setText("-");
            tfName.setText("");
            taGrades.setText("");
            lblPhotoVal.setText(defaultMsgPhoto);
            btUpdateStudent.setEnabled(false);
            btAddCard.setEnabled(false);
            return;
        }
        btUpdateStudent.setEnabled(true);
        btAddCard.setEnabled(false);

        lblIdVal.setText(selStd.getId() + "");
        tfName.setText(selStd.getName());
        taGrades.setText(selStd.getGradesListStr());
        lblGpa.setText(String.format("%.2f", selStd.getGpa()));
        if (selStd.getCard() == null) {
            lblPhotoVal.setIcon(null);
            lblPhotoVal.setText(defaultMsgPhoto);
            btAddCard.setEnabled(true);
            return;
        }
        lblPhotoVal.setIcon(new ImageIcon(selStd.getCard().getPhoto()));
    }//GEN-LAST:event_lstStudentsValueChanged

    private void btAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddStudentActionPerformed

        try {
            String name = tfName.getText();
            String grades = taGrades.getText();
            Student student = new Student(0, name, grades);
            db.addStudent(student);

            modelStudentList.clear();
            modelStudentList.addAll(db.getAllStudentList());
        } catch (InvalidDataException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Wrong Input data:" + ex.getMessage(),
                    "INVALID INPUT",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Data insert fail.\n" + ex.getMessage(),
                    "DATABASE FAIL",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_btAddStudentActionPerformed

    private void btUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateStudentActionPerformed
        Student selStd = lstStudents.getSelectedValue();
        if (selStd == null) {
            return;
        }
        try {
            String name = tfName.getText();
            String grades = taGrades.getText();
            Student student = new Student(selStd.getId(), name, grades);
            db.updateStudent(student);

            modelStudentList.clear();
            modelStudentList.addAll(db.getAllStudentList());
        } catch (InvalidDataException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Wrong Input data:" + ex.getMessage(),
                    "INVALID INPUT",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Data update fail.\n" + ex.getMessage(),
                    "DATABASE FAIL",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btUpdateStudentActionPerformed

    

    private void dlgCard_btAddCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgCard_btAddCardActionPerformed
        
        try {
            Student selStd = lstStudents.getSelectedValue();
            if (selStd == null) {
                return;
            }
        
            String permCode = dlgCard_tfPermCode.getText();
            Card card = new Card(0, permCode, bufImg);
            db.addCard(selStd.getId(), card);
        
            modelStudentList.clear();
            modelStudentList.addAll(db.getAllStudentList());
        
        } catch (InvalidDataException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Invalid data",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Add card fail.\n" + ex.getMessage(),
                    "DATABASE FAIL",
                    JOptionPane.ERROR_MESSAGE
            );
        } finally {
            this.setEnabled(true);
            dlgCard.dispose();
        }
    }//GEN-LAST:event_dlgCard_btAddCardActionPerformed

    private void dlgCard_lblPhotoValMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dlgCard_lblPhotoValMouseClicked
        // Choose Image with file chooser
        File chosenImgFile = chooseImageFile();
        if (chosenImgFile == null) {
            return;
        }

        // Check if file extention is in *.jpg, *.jpeg, *.gif, *.png
        if (!isValidImgFile(chosenImgFile)) {
            return;
        }

        // Read image file and convert it to 150x150 size
        //( getScaledInstance() method in Image Class with Image.SCALE_SMOOTH ) 
        try {
            BufferedImage originalImg = ImageIO.read(chosenImgFile);

            //convert it to 150x150 size with
            BufferedImage convertedImg = convertImgSize(originalImg);
            lblPhotoVal.setIcon(new ImageIcon(convertedImg));
            dlgCard_lblPhotoVal.setIcon(new ImageIcon(convertedImg));
            bufImg = convertedImg; // For saving/ editing member's info
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Cannot open Image file.",
                    "Reading File Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_dlgCard_lblPhotoValMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfoManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfoManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfoManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfoManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfoManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCard;
    private javax.swing.JButton btAddStudent;
    private javax.swing.JButton btUpdateStudent;
    private javax.swing.JDialog dlgCard;
    private javax.swing.JButton dlgCard_btAddCard;
    private javax.swing.JLabel dlgCard_lblIdVal;
    private javax.swing.JLabel dlgCard_lblPhotoVal;
    private javax.swing.JTextField dlgCard_tfPermCode;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JLabel lblIdVal;
    private javax.swing.JLabel lblPhotoVal;
    private javax.swing.JList<Student> lstStudents;
    private javax.swing.JTextArea taGrades;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
